version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      k8s:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
      bubbletea:
        patterns:
          - "github.com/charmbracelet/*"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci(deps)"
      include: "scope"
